import type { LaunchKit } from "./schema.js";

export function formatLaunchKitMarkdown(kit: LaunchKit): string {
  return [
    `# ${kit.meta.productName} Launch Kit`,
    "",
    `**Positioning:** ${kit.meta.positioning}`,
    `**Audience:** ${kit.meta.audience}`,
    "",
    "## GitHub README",
    kit.githubReadme,
    "",
    "## Product Hunt",
    `**Name:** ${kit.productHunt.name}`,
    `**Tagline:** ${kit.productHunt.tagline}`,
    "",
    kit.productHunt.description,
    "",
    "### Maker Comment",
    kit.productHunt.makerComment,
    "",
    "## Uneed",
    `**Title:** ${kit.uneed.title}`,
    `**Short Description:** ${kit.uneed.shortDescription}`,
    "",
    kit.uneed.launchPost,
    "",
    "## Gumroad",
    `**Title:** ${kit.gumroad.title}`,
    `**Subtitle:** ${kit.gumroad.subtitle}`,
    "",
    kit.gumroad.description,
    "",
    "### Included Files",
    ...kit.gumroad.includedFiles.map((item) => `- ${item}`),
    "",
    `**Pricing Note:** ${kit.gumroad.pricingNote}`,
    "",
    "## Hugging Face",
    `**Space Title:** ${kit.huggingFace.spaceTitle}`,
    `**Short Intro:** ${kit.huggingFace.shortIntro}`,
    "",
    kit.huggingFace.readmeBlurb,
    "",
    "## Launch Checklist",
    ...kit.checklist.map((item) => `- [ ] ${item}`),
    "",
    "## Outreach Email",
    kit.outreach.email,
    "",
    "## Social Posts",
    ...kit.outreach.socialPosts.map((post, index) => `### Post ${index + 1}\n${post}`)
  ].join("\n");
}
